FROM directus/directus:11.17.4

# Copy extensions and migrations into the image
# This ensures that they are part of the deployment package
COPY ./extensions /directus/extensions
COPY ./migrations /directus/migrations
