@echo off
echo Starting Docker containers...
docker compose up -d
echo Waiting for containers to initialize...
timeout /t 10 /nobreak
echo Creating Role "Finanzas App User"...
docker exec -i finanzas_db psql -U directus -d directus -c "INSERT INTO directus_roles (id, name, icon) VALUES (gen_random_uuid(), 'Finanzas App User', 'account_circle') ON CONFLICT DO NOTHING;"
echo Retrieving Role ID...
docker exec -i finanzas_db psql -U directus -d directus -t -c "SELECT id FROM directus_roles WHERE name = 'Finanzas App User';" > role_id.txt
echo Done. Role ID saved to role_id.txt
